POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ 
    "username": "adam1", 
    "password": "Pass1234!", 
    "email": "adam@mail.com" 
}

###

POST http://127.0.0.1:8000/login 
Content-Type: application/json

{ 
    "username": "adam1", 
    "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/testToken 
Content-Type: application/json Authorization: token xxx

###

GET https://backend-1qwg.onrender.com/inmuebles/ 
Content-Type: application/json

###

POST https://backend-1qwg.onrender.com/inmuebles/create/
Content-Type: application/json

{
    "apto": 1005,
    "unidad": "Kamelot",
    "ciudad": "Sabaneta",
    "precio": 2800000,
    "destinacion": "Arriendo",
    "habitaciones": 2,
    "area": 76,
    "extras": "Parqueo y cuarto útil",
    "llaves": "EN EL CASILLERO",
    "disponible": true
}

###

POST https://backend-1qwg.onrender.com/inmuebles/create/
Content-Type: application/json

{
    "apto": 2715
,
    "unidad": "RESERVA DEL BOSQUE",
    "ciudad": "ITAGÜÍ",
    "precio": 360000000,
    "destinacion": "Venta",
    "habitaciones": 2,
    "area": 63,
    "llaves": "Porteria",
    "disponible": true,
    "extras": "Parqueadero"
}

###

PATCH http://127.0.0.1:8000/inmuebles/3/update/
Content-Type: application/json

{   
    "precio": 2600000
}

###

DELETE http://127.0.0.1:8000/inmuebles/3/delete/
Content-Type: application/json

{   
    
}
