# Generated by Django 5.1.2 on 2024-11-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apto', models.IntegerField()),
                ('unidad', models.CharField(max_length=100)),
                ('torre', models.IntegerField(null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destinacion', models.CharField(max_length=100)),
                ('habitaciones', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extras', models.TextField(null=True)),
                ('llaves', models.CharField(default='Sin definir', max_length=100)),
                ('link', models.URLField(null=True)),
                ('bono', models.CharField(default='', max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
