# Generated by Django 5.1.2 on 2024-11-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
