# Generated by Django 5.1.2 on 2024-11-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles_app', '0002_alter_inmueble_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
